manifest:
  remotes:
    - name: urob
      url-base: https://github.com/urob
    - name: ssbb
      url-base: https://github.com/ssbb
  projects:
    - name: zmk
      url: ../../zmk
      revision: glove80
      clone-depth: 0
      import: app/west.yml
    - name: zmk-helpers
      remote: urob
      revision: main
    - name: zmk-auto-layer
      remote: urob
      revision: main
    - name: zmk-antecedent-morph
      remote: ssbb
      revision: main
  self:
    path: config
